#!/bin/sh
echo "Starting test runner..." 
cd "C:\Program Files\Microsoft Visual Studio\2022\Community\Common7\IDE\CommonExtensions\Microsoft\TestWindow"
failure_string="Failed:"
my_command="vstest.console.exe C:\Hai Dang\SENECA\SEMES 02\SFT221-new\Group\TestCode\Github Repo Test\testing001\SourceCode\ProjectX\x64\Debug\UnitTestY.dll
echo $my_command
output=$( $my_command )
echo "$output"
if [[ $output == *"$failure_string"* ]]; then 
	echo >&2 "Unit test are not passing! Push aborted!" 
	exit 1 
fi 
	echo >&2 "All tests run successfully." 
	exit 0
